class DummyUser {
  final int id;
  final String name;
  final int age;
  final String gender;
  final String country;
  final String migratedCountry;
  final List<String> skills;
  final List<String> interests;
  final String bio;
  final String profileImage;
  bool isConnected;

  DummyUser({
    required this.id,
    required this.name,
    required this.age,
    required this.gender,
    required this.country,
    required this.migratedCountry,
    required this.skills,
    required this.interests,
    required this.bio,
    required this.profileImage,
    required this.isConnected,
  });
}

final List<DummyUser> dummyUsers = [
  DummyUser(
    id: 1,
    name: "Aarav Patel",
    age: 22,
    gender: "Male",
    country: "India",
    migratedCountry: "Canada",
    skills: ["React", "Node.js", "MongoDB"],
    interests: ["Startups", "AI", "Cricket"],
    bio: "Passionate about building scalable tech products and exploring new AI trends.",
    profileImage: "https://via.placeholder.com/150/003366/FFFFFF?text=AP",
    isConnected: false,
  ),
  DummyUser(
    id: 2,
    name: "Sarah Smith",
    age: 24,
    gender: "Female",
    country: "UK",
    migratedCountry: "USA",
    skills: ["Python", "Data Science", "SQL"],
    interests: ["Machine Learning", "Reading", "Traveling"],
    bio: "Data enthusiast looking to connect with other analysts and data scientists.",
    profileImage: "https://via.placeholder.com/150/FF6B6B/FFFFFF?text=SS",
    isConnected: true,
  ),
  DummyUser(
    id: 3,
    name: "Michael Lee",
    age: 21,
    gender: "Male",
    country: "China",
    migratedCountry: "Australia",
    skills: ["Flutter", "Dart", "Firebase"],
    interests: ["Mobile Dev", "Gaming", "Music"],
    bio: "Aspiring mobile developer who loves building beautiful cross-platform apps.",
    profileImage: "https://via.placeholder.com/150/4ECDC4/FFFFFF?text=ML",
    isConnected: false,
  ),
  DummyUser(
    id: 4,
    name: "Emily Davis",
    age: 23,
    gender: "Female",
    country: "Canada",
    migratedCountry: "UK",
    skills: ["UI/UX Design", "Figma", "CSS"],
    interests: ["Design", "Art", "Photography"],
    bio: "Creative designer focused on user-centered experiences and minimal interfaces.",
    profileImage: "https://via.placeholder.com/150/FFA07A/FFFFFF?text=ED",
    isConnected: false,
  ),
  DummyUser(
    id: 5,
    name: "David Wilson",
    age: 25,
    gender: "Male",
    country: "Australia",
    migratedCountry: "Germany",
    skills: ["C++", "Java", "System Architecture"],
    interests: ["Backend", "Open Source", "Hiking"],
    bio: "Software engineer passionate about high-performance backend systems.",
    profileImage: "https://via.placeholder.com/150/9370DB/FFFFFF?text=DW",
    isConnected: false,
  ),
  DummyUser(
    id: 6,
    name: "Jessica Brown",
    age: 20,
    gender: "Female",
    country: "USA",
    migratedCountry: "Canada",
    skills: ["HTML", "CSS", "JavaScript"],
    interests: ["Frontend", "Blogging", "Coffee"],
    bio: "Learning the ropes of web development. Always down for a coffee chat!",
    profileImage: "https://via.placeholder.com/150/20B2AA/FFFFFF?text=JB",
    isConnected: false,
  ),
  DummyUser(
    id: 7,
    name: "Ravi Kumar",
    age: 26,
    gender: "Male",
    country: "India",
    migratedCountry: "Germany",
    skills: ["DevOps", "AWS", "Docker", "Kubernetes"],
    interests: ["Cloud", "Automation", "Chess"],
    bio: "DevOps engineer making deployments smoother and more reliable.",
    profileImage: "https://via.placeholder.com/150/FFD700/000000?text=RK",
    isConnected: true,
  ),
  DummyUser(
    id: 8,
    name: "Sophie Martin",
    age: 22,
    gender: "Female",
    country: "France",
    migratedCountry: "USA",
    skills: ["Marketing", "SEO", "Content Writing"],
    interests: ["Digital Marketing", "Social Media", "Fashion"],
    bio: "Creative marketer helping tech startups grow their online presence.",
    profileImage: "https://via.placeholder.com/150/FF69B4/FFFFFF?text=SM",
    isConnected: false,
  ),
  DummyUser(
    id: 9,
    name: "Liam O'Connor",
    age: 24,
    gender: "Male",
    country: "Ireland",
    migratedCountry: "Australia",
    skills: ["Project Management", "Agile", "Scrum"],
    interests: ["Leadership", "Productivity", "Rugby"],
    bio: "Scrum master dedicated to helping teams deliver their best work.",
    profileImage: "https://via.placeholder.com/150/32CD32/FFFFFF?text=LO",
    isConnected: false,
  ),
  DummyUser(
    id: 10,
    name: "Yuki Tanaka",
    age: 23,
    gender: "Female",
    country: "Japan",
    migratedCountry: "UK",
    skills: ["Swift", "iOS Dev", "Objective-C"],
    interests: ["Apple Tech", "Anime", "Cooking"],
    bio: "iOS Developer building fluid and engaging mobile experiences.",
    profileImage: "https://via.placeholder.com/150/8A2BE2/FFFFFF?text=YT",
    isConnected: false,
  ),
  DummyUser(
    id: 11,
    name: "Omar Ali",
    age: 27,
    gender: "Male",
    country: "Egypt",
    migratedCountry: "Canada",
    skills: ["Cybersecurity", "Networking", "Linux"],
    interests: ["Security", "Ethical Hacking", "History"],
    bio: "Cybersecurity enthusiast focused on protecting user data and privacy.",
    profileImage: "https://via.placeholder.com/150/DC143C/FFFFFF?text=OA",
    isConnected: false,
  ),
  DummyUser(
    id: 12,
    name: "Chloe Tremblay",
    age: 21,
    gender: "Female",
    country: "Canada",
    migratedCountry: "USA",
    skills: ["Vue.js", "Tailwind", "TypeScript"],
    interests: ["Web Design", "Animals", "Yoga"],
    bio: "Frontend dev who loves crafting beautiful and responsive UIs with Vue.",
    profileImage: "https://via.placeholder.com/150/00CED1/FFFFFF?text=CT",
    isConnected: false,
  ),
  DummyUser(
    id: 13,
    name: "Hans Schmidt",
    age: 25,
    gender: "Male",
    country: "Germany",
    migratedCountry: "Australia",
    skills: ["Mechanical Engineering", "CAD", "Robotics"],
    interests: ["Automation", "Automotive", "Beer"],
    bio: "Engineer with a passion for robotics and automating real-world tasks.",
    profileImage: "https://via.placeholder.com/150/FF8C00/FFFFFF?text=HS",
    isConnected: false,
  ),
  DummyUser(
    id: 14,
    name: "Mia Rossi",
    age: 22,
    gender: "Female",
    country: "Italy",
    migratedCountry: "UK",
    skills: ["Business Analysis", "Excel", "Tableau"],
    interests: ["Finance", "Data Viz", "Travel"],
    bio: "Analyst translating complex datasets into actionable business insights.",
    profileImage: "https://via.placeholder.com/150/C71585/FFFFFF?text=MR",
    isConnected: false,
  ),
  DummyUser(
    id: 15,
    name: "Lucas Silva",
    age: 26,
    gender: "Male",
    country: "Brazil",
    migratedCountry: "Germany",
    skills: ["Ruby on Rails", "PostgreSQL", "Redis"],
    interests: ["Backend", "Open Source", "Football"],
    bio: "Backend developer scaling Ruby applications and contributing to open source.",
    profileImage: "https://via.placeholder.com/150/2E8B57/FFFFFF?text=LS",
    isConnected: true,
  )
];
