// This file can provide convenient mock data for UI testing.

import 'user.dart';
import 'student_profile.dart';
import 'parent_profile.dart';
import 'post.dart';
import 'ad.dart';
import 'group.dart';

class MockData {
  static final List<User> users = [
    User(
      id: "u1",
      name: "Rohan Sharma",
      email: "rohan.sharma@example.com",
      university: "Berlin University",
      course: "MSc Computer Science",
      currentCity: "Berlin",
      originCity: "Mumbai",
      migratedCountry: "Germany",
      company: null,
      jobRole: null,
    ),
    User(
      id: "u2",
      name: "Priya Patel",
      email: "priya.patel@example.com",
      university: "Technical University of Munich",
      course: "Data Science",
      currentCity: "Munich",
      originCity: "Ahmedabad",
      migratedCountry: "Germany",
      company: null,
      jobRole: null,
    ),
    User(
      id: "u3",
      name: "Amit Kumar",
      email: "amit.kumar@example.com",
      university: "University of Toronto",
      course: "MBA",
      currentCity: "Toronto",
      originCity: "Delhi",
      migratedCountry: "Canada",
      company: "Tech Solutions",
      jobRole: "Product Manager",
    ),
    User(
      id: "u4",
      name: "Sneha Reddy",
      email: "sneha.reddy@example.com",
      university: "University of Melbourne",
      course: "Information Technology",
      currentCity: "Melbourne",
      originCity: "Hyderabad",
      migratedCountry: "Australia",
      company: null,
      jobRole: null,
    ),
    User(
      id: "u5",
      name: "Arjun Singh",
      email: "arjun.singh@example.com",
      university: "Oxford University",
      course: "Finance",
      currentCity: "Oxford",
      originCity: "Chandigarh",
      migratedCountry: "UK",
      company: "Global Bank",
      jobRole: "Financial Analyst",
    ),
    User(
      id: "u6",
      name: "Aisha Khan",
      email: "aisha.khan@example.com",
      university: "Technical University of Munich",
      course: "Data Science",
      currentCity: "Munich",
      originCity: "Delhi",
      migratedCountry: "Germany",
      company: null,
      jobRole: null,
    ),
    User(
      id: "u7",
      name: "Wei Chen",
      email: "wei.chen@example.com",
      university: "Berlin University",
      course: "MSc Computer Science",
      currentCity: "Berlin",
      originCity: "Beijing",
      migratedCountry: "Germany",
      company: null,
      jobRole: null,
    ),
    User(
      id: "u8",
      name: "David Smith",
      email: "david.smith@example.com",
      university: "University of Toronto",
      course: "MBA",
      currentCity: "Toronto",
      originCity: "London",
      migratedCountry: "Canada",
      company: null,
      jobRole: null,
    ),
    User(
      id: "u9",
      name: "Maria Garcia",
      email: "maria.garcia@example.com",
      university: "University of Melbourne",
      course: "Information Technology",
      currentCity: "Melbourne",
      originCity: "Madrid",
      migratedCountry: "Australia",
      company: null,
      jobRole: null,
    ),
    User(
      id: "u10",
      name: "James Taylor",
      email: "james.taylor@example.com",
      university: "Oxford University",
      course: "Economics",
      currentCity: "Oxford",
      originCity: "New York",
      migratedCountry: "UK",
      company: null,
      jobRole: null,
    ),
    User(
      id: "u11",
      name: "Neha Gupta",
      email: "neha.gupta@example.com",
      university: "Berlin University",
      course: "Data Science",
      currentCity: "Berlin",
      originCity: "Mumbai",
      migratedCountry: "Germany",
      company: null,
      jobRole: null,
    ),
    User(
      id: "u12",
      name: "Rahul Verma",
      email: "rahul.verma@example.com",
      university: "University of Melbourne",
      course: "Finance",
      currentCity: "Melbourne",
      originCity: "Hyderabad",
      migratedCountry: "Australia",
      company: "Tech Finance Corp",
      jobRole: "Junior Analyst",
    ),
  ];

  static final Post samplePost = Post(
    postId: 'p1',
    userId: 'u1',
    content: 'Just arrived in Germany! Excited to start my master\'s journey at Berlin University.',
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    visibility: PostVisibility.public,
  );

  static final List<Ad> ads = [
    Ad(
      adId: 'ad1',
      title: 'Ad 1',
      description: 'Special offer 1',
      imageUrl: 'assets/ad 1.jpeg',
      targetCountry: 'Global',
      startDate: DateTime.now(),
      endDate: DateTime.now().add(const Duration(days: 30)),
      createdAt: DateTime.now(),
    ),
    Ad(
      adId: 'ad2',
      title: 'Ad 2',
      description: 'Special offer 2',
      imageUrl: 'assets/ad 2.jpeg',
      targetCountry: 'Global',
      startDate: DateTime.now(),
      endDate: DateTime.now().add(const Duration(days: 30)),
      createdAt: DateTime.now(),
    ),
    Ad(
      adId: 'ad3',
      title: 'Ad 3',
      description: 'Special offer 3',
      imageUrl: 'assets/ad 3.webp',
      targetCountry: 'Global',
      startDate: DateTime.now(),
      endDate: DateTime.now().add(const Duration(days: 30)),
      createdAt: DateTime.now(),
    ),
    Ad(
      adId: 'ad4',
      title: 'Ad 4',
      description: 'Special offer 4',
      imageUrl: 'assets/ad 4.png',
      targetCountry: 'Global',
      startDate: DateTime.now(),
      endDate: DateTime.now().add(const Duration(days: 30)),
      createdAt: DateTime.now(),
    ),
    Ad(
      adId: 'ad5',
      title: 'Ad 5',
      description: 'Special offer 5',
      imageUrl: 'assets/ad 5.jpeg',
      targetCountry: 'Global',
      startDate: DateTime.now(),
      endDate: DateTime.now().add(const Duration(days: 30)),
      createdAt: DateTime.now(),
    ),
  ];

  static final List<Group> cityGroups = [
    Group(
      groupId: 'g_city1',
      name: 'Berlin Explorers',
      description: 'Find friends and events in Berlin.',
      type: GroupType.topic,
      createdBy: 'u1',
      createdAt: DateTime.now(),
    ),
    Group(
      groupId: 'g_city2',
      name: 'Munich Locals',
      description: 'Connect with people in Munich.',
      type: GroupType.topic,
      createdBy: 'u2',
      createdAt: DateTime.now(),
    ),
  ];

  static final List<Group> originCityGroups = [
    Group(
      groupId: 'g_origin1',
      name: 'Mumbai to Germany',
      description: 'Connect with folks from Mumbai.',
      type: GroupType.topic,
      createdBy: 'u1',
      createdAt: DateTime.now(),
    ),
    Group(
      groupId: 'g_origin2',
      name: 'Delhi NCR Students',
      description: 'For students hailing from Delhi.',
      type: GroupType.topic,
      createdBy: 'u3',
      createdAt: DateTime.now(),
    ),
  ];

  static final List<Group> universityGroups = [
    Group(
      groupId: 'g_uni1',
      name: 'Berlin Uni Fall 2026',
      description: 'Join your batchmates at Berlin University.',
      type: GroupType.university,
      createdBy: 'u1',
      createdAt: DateTime.now(),
    ),
    Group(
      groupId: 'g_uni2',
      name: 'TUM Grads',
      description: 'Network with other TUM students.',
      type: GroupType.university,
      createdBy: 'u2',
      createdAt: DateTime.now(),
    ),
  ];
}
